exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

title: Romain Tavenard
theme: jekyll-theme-primer
defaults:
  - scope:
      path: "assets/scans"
    values:
      scan: true
