exclude:
  - node_modules
  - script

sass:
  style: :compressed

title: Romain Tavenard
theme: jekyll-theme-primer
defaults:
  - scope:
      path: "assets/scans"
    values:
      scan: true

gems: ['jekyll/scholar']
plugins_dir: [jekyll-scholar]

scholar:
  style: apa-no-doi-no-issue
  locale: en

  sort_by: year, month
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  query: "@*"
